version: '3.3'
services:
    dns-updater:
        container_name: dns-updater
        image: rafaelquines/dynip-do-dns-updater
        environment:
            - DO_API_KEY=${DO_API_KEY}
            - DOMAIN_NAME=${DOMAIN_NAME}
            - RECORD_TYPE=${RECORD_TYPE}
            - RECORD_NAME=${RECORD_NAME}
            - INTERVAL=${INTERVAL}
            - LOCAL_INTERFACE=${LOCAL_INTERFACE}
        restart: always
        network_mode: host